#! /bin/bash
BLD="\e[01;39m"
RED="\e[01;31m"
GRN="\e[01;32m"
BLU="\e[01;34m"
YLW="\e[01;33m"
YLWB="\e[00;33m"
C="\e[02;37m"
C2="$BLD\e[00;36m"
RST="\e[00m"
R="\e[00m"
UND="\e[04;37m"
ITA="\e[03;37m"
BCK="\e[07;37m"
BRED="$BLD\e[07;31m"
BGRE="$BLD\e[07;32m"
BBLU="$BLD\e[07;34m"
BPUR="$BLD\e[07;35m"
BYLW="$BLD\e[07;33m"

HT=$BLD' o '$RST
HR=$BRED' R '$RST
HBLUES=$C'(·)'$RST

CP=$BCK' │ '$R$C
NO=$C' X '
H1=$BRED' 1 '$R$C
H3=$BGRE' 3 '$R$C
H5=$BBLU' 5 '$R$C
H7=$BPUR' 7 '$R$C
Hb3=$BGRE'♭3 '$R$C
Hb5=$BBLU'♭5 '$R$C
Hb7=$BPUR'♭7 '$R$C
Hbb7=$BPUR'♭♭7'$R$C
Hs5=$BBLU'♯5 '$R$C
H4=$BYLW' 4 '$R$C
Hb9=$BYLW'♭9 '$R$C
Hs11=$BYLW'♯11'$R$C
Hb13=$BYLW'♭13'$R$C

SHOWCHORDS="OFF"
PDF="OFF"
ONLYCHORDS="OFF"

BAN="$GRN
                                      dP
                                      88
           .d8888b. .d8888b. .d8888b. 88 .d8888b.
           Y8ooooo. 88'  ''' 88'  '88 88 88ooood8
                 88 88.  ... 88.  .88 88 88.  ...
           '88888P' '88888P' '88888P8 dP '88888P'
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo$R"

HELP="$BLD
    "$UND$BLU"USAGE:$R

        "$BLD"scale [SCALE]$R   display musical scale information
                        and its guitar patterns

        "$BLD"scale help$R      display this help and exit
        "$BLD"scale list$R      list all available scales

        "$BLD"scale [SCALE] [OPTION]...$R
            scale major
            scale major chords
            scale major chords pdf

        "$BLD"scale [ROOTNOTE] [SCALE] [OPTION]...$R
            scale A major
            scale D minor chords
            scale F# melodic mode 1 pdf
            scale Bb harmonic mode 4 onlychords pdf

    "$BLD$BLU"ROOTNOTES:$R
        A, Ab, A#, B, Bb, C, Cb, C# ...

    "$BLD$BLU"SCALES:$R
        major, minor, mixloydianb9b13, lydian#5 ...
        melodic mode1, natural mode4, harmonic mode6 ...
        ...
        (use '"$BLD$UND"scale list$R' to show the complete list)

    "$BLD$BLU"OPTIONS:$R
        "$BLD"chords$R          show the scale and its diatonic chords
        "$BLD"onlychords$R      display only the diatonic chords
        "$BLD"pdf$R             save the output as a PDF

"

AVAILABLE="
"$BLD$UND$BLU"AVAILABLE [SCALE] LIST:$RST

"$BLD$BBLU"Basics:$RST
    major                     $C==$R  natural mode1
    minor, natural minor      $C==$R  natural mode6
    melodic, melodic minor    $C==$R  melodic mode1
    harmonic, harmonic minor  $C==$R  harmonic mode1
    major pentatonic
    minor pentatonic

"$BLD$BBLU"Natural modes:$RST
    natural mode1   $C==$R  major, ionian
    natural mode2   $C==$R  dorian
    natural mode3   $C==$R  phrygian
    natural mode4   $C==$R  lydian
    natural mode5   $C==$R  mixolydian
    natural mode6   $C==$R  minor, aeolian, natural minor
    natural mode7   $C==$R  locrian

"$BLD$BBLU"Harmonic modes:$RST
    harmonic mode1  $C==$R  harmonic minor
    harmonic mode2  $C==$R  locrian#13
    harmonic mode3  $C==$R  ionian#5, augmented major
    harmonic mode4  $C==$R  dorian#11, altered dorian
                        ukranian dorian, romanian minor
    harmonic mode5  $C==$R  phrygian dominant, mixolydian b9b13
    harmonic mode6  $C==$R  lydian#9
    harmonic mode7  $C==$R  altered diminished, locrian b11b7


"$BLD$BBLU"Melodic modes:$RST
    melodic mode1   $C==$R  melodic minor, jazz minor
    melodic mode2   $C==$R  dorian b9, phrygian#13
    melodic mode3   $C==$R  lydian augmented, lydian#5
    melodic mode4   $C==$R  lydian dominant, lydian b7, overtone
    melodic mode5   $C==$R  mixolydian b13, hindu
    melodic mode6   $C==$R  aeolian b5, locrian#9, half diminished
    melodic mode7   $C==$R  altered, super locrian
                        locrian b11, diminished wholetone

"


################################################################
## Display HELP or LIST:
echo $1 | grep -oqE "^([A-G]$|[A-G][#,b]$|major$|minor$|natural|melodic|harmonic|ionian$|dorian$|phrygian$|lydian$|mixolydian$|aeolian$|locrian$|ionian[b,#]|dorian[b,#]|phrygian[b,#]|lydian[b,#]|mixolydian[b,#]|aeolian[b,#]|locrian[b,#]|jazz$|jazzminor$|lydianaugmented$|lydiandominant$|overtone$|hindu$|half$|halfdiminished$|altered$|super$|superlocrian$|diminished$|diminishedwholetone$|augmented$|augmentedmajor$|ukranian$|ukraniandorian$|romanian$|romanianminor$|altereddorian$|phrygiandominant$|superlocrian$|altereddiminished$|majorpentatonic$|minorpentatonic$|--list|-l|list)"
if [ $? != 0 ]
then
    echo -e "$BAN"
    echo -e "$HELP"
    exit;
fi
if [ $1 = "-l" ]|| [ $1 = "--list" ] || [ $1 = "list" ];then echo -e "$AVAILABLE";exit;fi

################################################################
## Getting the values from the input arguments;
echo $1 | grep -oqE "^([A-G]|[A-G][#,b])"
if [[ $? = 0 ]]; then
    ROOT=$1
    INNOTE=$(echo $1 | grep -oE "^([A-G])")
else
    ROOT="OFF"
fi

for ARG in "$@"; do
    if [ $ARG != "$ROOT" ] && [ $ARG != "chords" ] && [ $ARG != "--chords" ] && [ $ARG != "pdf" ] && [ $ARG != "--pdf" ] && [ $ARG != "onlychords" ]; then
        SCALE=$SCALE$ARG
    elif [ $ARG = "chords" ] || [ $ARG = "--chords" ]; then
        SHOWCHORDS="ON"
    elif [ $ARG = "pdf" ] || [ $ARG = "--pdf" ]; then
        PDF="ON"
    elif [ $ARG = "onlychords" ]; then
        ONLYCHORDS="ON"
        SHOWCHORDS="ON"
    fi
done

################################################################
# Set FAMILY and MODE if found:
echo $SCALE | grep -oqE "(natural|melodic|harmonic)"
if [ $? = 0 ];then
FAMILY=$(echo $SCALE | grep -oE "(natural|melodic|harmonic)")
fi

echo $SCALE | grep -oqE "mode[1-7]"
if [ $? = 0 ];then
MODE=$(echo $SCALE | grep -oE "mode[1-7]")
fi

# Re-set the mode number if it is a melodic or harmonic type, to match with ionian relative modes
if [[ -n $FAMILY ]]; then
    if [[ $FAMILY = harmonic ]] || [[ $FAMILY = melodic ]];then
        if [[ -z $MODE ]]; then MODE="1";fi
        MODENUM=$(echo $MODE | grep -oE "[1-7]")
        if [ "$MODENUM" -gt "2" ]; then
            MODENUM=$(($MODENUM-2))
            MODE="mode$MODENUM"
        elif [ "$MODENUM" -lt "3" ]; then
            MODENUM=$(($MODENUM+5))
            MODE="mode$MODENUM"
        fi
    fi
fi

#############################################################
## SETTING COMMON FRETS:

F=───
declare F{1..567}="$F"
declare F1{11,12,14,24,31,33,41,43,44,51,61,62,64}="$HT"
declare F2{12,14,22,24,25,31,41,42,44,54,62,64}="$HT"
declare F3{11,21,22,24,33,41,43,51,53,54,61}="$HT"
declare F4{14,22,24,31,33,34,41,51,52,54,64}="$HT"
declare F5{12,14,15,22,31,32,34,44,52,54,62,64,65}="$HT"

## Setting $FAMILY & $MODE groups:
case $SCALE in
    natural|major|minor|naturalminor|ionian|dorian|phrygian|lydian|mixolydian|aeolian|locrian)
        FAMILY="natural"
        ;;
    melodic|melodicminor|jazzminor|dorianb9|phrygian#13|lydianaugmented|lydian#5|lydiandominant|lydianb7|overtone|mixolydianb13|hindu|aeolianb5|locrian#9|halfdiminished|altered|superlocrian|locrianb11|diminishedwholetone)
        FAMILY="melodic"
        ;;
    harmonic|harmonicminor|locrian#13|ionian#5|augmentedmajor|dorian#11|ukraniandorian|ukranian|romanian|romanianminor|altereddorian|phrygiandominant|mixolydianb9b13|lydian#9|altereddiminished|locrianb11b7)
        FAMILY="harmonic"
        ;;
esac

case $SCALE in
    mode1|ionian|major|lydianaugmented|lydian#5|ionian#5|augmentedmajor)
        MODE="mode1"
        ;;
    mode2|dorian|lydiandominant|lydianb7|overtone|dorian#11|ukraniandorian|ukranian|romanian|romanianminor|altereddorian)
        MODE="mode2"
        ;;
    mode3|phrygian|mixolydianb13|hindu|phrygiandominant|mixolydianb9b13)
        MODE="mode3"
        ;;
    mode4|lydian|aeolianb5|locrian#9|halfdiminished|lydian#9)
        MODE="mode4"
        ;;
    mode5|mixolydian|altered|locrianb11|diminishedwholetone|superlocrian|altereddiminished|locrianb11b7)
        MODE="mode5"
        ;;
    mode6|aeolian|minor|natural|naturalminor|melodic|melodicminor|harmonic|harmonicminor|jazzminor)
        MODE="mode6"
        ;;
    mode7|locrian|dorianb9|phrygian#13|locrian#13)
        MODE="mode7"
        ;;
esac

#############################################################
## SETTING UNCOMMON FRETS,
#  Setting 6th & 7th notes (relative to aeolian) based on $FAMILY (same for each mode), define intervals-value info, and setting a default ROOT if unset:
case $FAMILY in
    natural)
        declare F1{22,34,52,54}="$HT"
        declare F2{15,32,34,52,65}="$HT"
        declare F3{12,14,31,44,62,64}="$HT"
        declare F4{12,25,42,44,62}="$HT"
        declare F5{23,25,42,55}="$HT"
        INTERVAL1=" 1 ";INTERVAL2=" 1 ";INTERVAL3=" ½ ";INTERVAL4=" 1 ";INTERVAL5=" 1 ";INTERVAL6=" 1 ";INTERVAL7=" ½ "
        if [ $ROOT = "OFF" ]; then KEY="104";INNOTE="GRADES";fi
        ;;
    melodic)
        declare F1{21,23,53,55}="$HT"
        declare F2{33,35,51,53}="$HT"
        declare F3{13,15,32,45,63,65}="$HT"
        declare F4{11,13,43,45,61,63}="$HT"
        declare F5{11,24,41,43,61}="$HT"
        INTERVAL1=" 1 ";INTERVAL2=" 1 ";INTERVAL3=" 1 ";INTERVAL4=" 1 ";INTERVAL5=" ½ ";INTERVAL6=" 1 ";INTERVAL7=" ½ "
        if [ $ROOT = "OFF" ]; then KEY="101";INNOTE="GRADES";fi
        ;;
    harmonic)
        declare F1{23,34,52,55}="$HT"
        declare F2{15,32,35,53,65}="$HT"
        declare F3{12,15,32,44,62,65}="$HT"
        declare F4{13,25,42,45,63}="$HT"
        declare F5{11,23,43,55,61}="$HT"
        INTERVAL1=" 1 ";INTERVAL2=" 1 ";INTERVAL3=" ½ ";INTERVAL4="1½ ";INTERVAL5=" ½ ";INTERVAL6=" 1 ";INTERVAL7=" ½ "
        if [ $ROOT = "OFF" ]; then KEY="101";INNOTE="GRADES";fi
        ;;
esac

#  Setting root $HR, the display-order, and the interval-info-order based on $MODE (same for each family, except for modes 4 & 5):
case $MODE in
    mode1)
        declare F1{12,44,62}="$HR"
        declare F2{25,42}="$HR"
        declare F3{22,54}="$HR"
        declare F4{34,52}="$HR"
        declare F5{15,32,65}="$HR"
        ORDER="1"
        in1="$INTERVAL1";in2="$INTERVAL2";in3="$INTERVAL3";in4="$INTERVAL4";in5="$INTERVAL5";in6="$INTERVAL6";in7="$INTERVAL7"
        ;;
    mode2)
        declare F1{14,31,64}="$HR"
        declare F2{12,44,62}="$HR"
        declare F3{24,41}="$HR"
        declare F4{22,54}="$HR"
        declare F5{34,52}="$HR"
        ORDER="2"
        in1="$INTERVAL2";in2="$INTERVAL3";in3="$INTERVAL4";in4="$INTERVAL5";in5="$INTERVAL6";in6="$INTERVAL7";in7="$INTERVAL1"
        ;;
    mode3)
        declare F1{33,51}="$HR"
        declare F2{14,31,64}="$HR"
        declare F3{11,43,61}="$HR"
        declare F4{24,41}="$HR"
        declare F5{22,54}="$HR"
        ORDER="3"
        in1="$INTERVAL3";in2="$INTERVAL4";in3="$INTERVAL5";in4="$INTERVAL6";in5="$INTERVAL7";in6="$INTERVAL1";in7="$INTERVAL2"
        ;;
    mode4)
        if [ "$FAMILY" = "melodic" ]; then
            declare F1{21,53}="$HR"
            declare F2{33,51}="$HR"
            declare F3{13,45,63}="$HR"
            declare F4{11,43,61}="$HR"
            declare F5{24,41}="$HR"
        else
            declare F1{34,52}="$HR"
            declare F2{15,32,65}="$HR"
            declare F3{12,44,62}="$HR"
            declare F4{25,42}="$HR"
            declare F5{23,55}="$HR"
        fi
        ORDER="3"
        in1="$INTERVAL4";in2="$INTERVAL5";in3="$INTERVAL6";in4="$INTERVAL7";in5="$INTERVAL1";in6="$INTERVAL2";in7="$INTERVAL3"
        ;;
    mode5)
        if [ "$FAMILY" = "natural" ]; then
            declare F1{22,54}="$HR"
            declare F2{34,52}="$HR"
            declare F3{14,31,64}="$HR"
            declare F4{12,44,62}="$HR"
            declare F5{25,42}="$HR"
        else
            declare F1{23,55}="$HR"
            declare F2{35,53}="$HR"
            declare F3{15,32,65}="$HR"
            declare F4{13,45,63}="$HR"
            declare F5{11,43,61}="$HR"
        fi
        ORDER="4"
        in1="$INTERVAL5";in2="$INTERVAL6";in3="$INTERVAL7";in4="$INTERVAL1";in5="$INTERVAL2";in6="$INTERVAL3";in7="$INTERVAL4"
        ;;
    mode6)
        declare F1{24,41}="$HR"
        declare F2{22,54}="$HR"
        declare F3{33,51}="$HR"
        declare F4{14,31,64}="$HR"
        declare F5{12,44,62}="$HR"
        ORDER="5"
        in1="$INTERVAL6";in2="$INTERVAL7";in3="$INTERVAL1";in4="$INTERVAL2";in5="$INTERVAL3";in6="$INTERVAL4";in7="$INTERVAL5"
        ;;
    mode7)
        declare F1{11,43,61}="$HR"
        declare F2{24,41}="$HR"
        declare F3{21,53}="$HR"
        declare F4{33,51}="$HR"
        declare F5{14,31,64}="$HR"
        ORDER="1"
        in1="$INTERVAL7";in2="$INTERVAL1";in3="$INTERVAL2";in4="$INTERVAL3";in5="$INTERVAL4";in6="$INTERVAL5";in7="$INTERVAL6"
        ;;
esac

################################################################
#ADDING PENTATONIC SCALES
case $SCALE in
minorpentatonic|minorbluespentatonic)
        declare F{1..567}="$F"
        declare F1{12,14,22,24,31,33,41,44,51,54,62,64}="$HT"
        declare F2{12,14,22,25,31,34,42,44,52,54,62,64}="$HT"
        declare F3{11,14,22,24,31,33,41,43,51,54,61,64}="$HT"
        declare F4{12,14,22,24,31,34,41,44,52,54,62,64}="$HT"
        declare F5{12,15,22,25,32,34,42,44,52,54,62,65}="$HT"
        declare F1{15,32,65}="$HBLUES"
        declare F2{13,45,63}="$HBLUES"
        declare F3{25,42}="$HBLUES"
        declare F4{23,55}="$HBLUES"
        declare F5{35,53}="$HBLUES"
        declare F1{24,41}="$HR"
        declare F2{22,54}="$HR"
        declare F3{33,51}="$HR"
        declare F4{14,31,64}="$HR"
        declare F5{12,44,62}="$HR"
        ORDER="5"
        in1="1½ ";in2="$C───";in3=" 1 ";in4=" ½ ";in5=" ½ ";in6="1½ ";in7=" 1 "
        if [ $ROOT = "OFF" ]; then KEY="101";INNOTE="PENTAGRADES";fi
        ;;
majorpentatonic|majorbluespentatonic)
        declare F{1..567}="$F"
        declare F1{12,14,22,24,31,33,41,44,51,54,62,64}="$HT"
        declare F2{12,14,22,25,31,34,42,44,52,54,62,64}="$HT"
        declare F3{11,14,22,24,31,33,41,43,51,54,61,64}="$HT"
        declare F4{12,14,22,24,31,34,41,44,52,54,62,64}="$HT"
        declare F5{12,15,22,25,32,34,42,44,52,54,62,65}="$HT"
        declare F1{15,32,65}="$HBLUES"
        declare F2{13,45,63}="$HBLUES"
        declare F3{25,42}="$HBLUES"
        declare F4{23,55}="$HBLUES"
        declare F5{35,53}="$HBLUES"
        declare F1{12,44,62}="$HR"
        declare F2{25,42}="$HR"
        declare F3{22,54}="$HR"
        declare F4{34,52}="$HR"
        declare F5{15,32,65}="$HR"
        ORDER="1"
        in6="1½ ";in7="$C───";in1=" 1 ";in2=" ½ ";in3=" ½ ";in4="1½ ";in5=" 1 "
        if [ $ROOT = "OFF" ]; then KEY="104";INNOTE="PENTAGRADES";fi
        ;;
esac

#############################################################
## SETTING THE GRIDS

GRID1S1="$C┌─$F111$C─┬─$F112$C─┬─$F113$C─┬─$F114$C─┬─$F115$C─┐$RST"
GRID1S2="$C├─$F121$C─┼─$F122$C─┼─$F123$C─┼─$F124$C─┼─$F125$C─┤$RST"
GRID1S3="$C├─$F131$C─┼─$F132$C─┼─$F133$C─┼─$F134$C─┼─$F135$C─┤$RST"
GRID1S4="$C├─$F141$C─┼─$F142$C─┼─$F143$C─┼─$F144$C─┼─$F145$C─┤$RST"
GRID1S5="$C├─$F151$C─┼─$F152$C─┼─$F153$C─┼─$F154$C─┼─$F155$C─┤$RST"
GRID1S6="$C└─$F161$C─┴─$F162$C─┴─$F163$C─┴─$F164$C─┴─$F165$C─┘$RST"

GRID2S1="$C┌─$F211$C─┬─$F212$C─┬─$F213$C─┬─$F214$C─┬─$F215$C─┐$RST"
GRID2S2="$C├─$F221$C─┼─$F222$C─┼─$F223$C─┼─$F224$C─┼─$F225$C─┤$RST"
GRID2S3="$C├─$F231$C─┼─$F232$C─┼─$F233$C─┼─$F234$C─┼─$F235$C─┤$RST"
GRID2S4="$C├─$F241$C─┼─$F242$C─┼─$F243$C─┼─$F244$C─┼─$F245$C─┤$RST"
GRID2S5="$C├─$F251$C─┼─$F252$C─┼─$F253$C─┼─$F254$C─┼─$F255$C─┤$RST"
GRID2S6="$C└─$F261$C─┴─$F262$C─┴─$F263$C─┴─$F264$C─┴─$F265$C─┘$RST"

GRID3S1="$C┌─$F311$C─┬─$F312$C─┬─$F313$C─┬─$F314$C─┬─$F315$C─┐$RST"
GRID3S2="$C├─$F321$C─┼─$F322$C─┼─$F323$C─┼─$F324$C─┼─$F325$C─┤$RST"
GRID3S3="$C├─$F331$C─┼─$F332$C─┼─$F333$C─┼─$F334$C─┼─$F335$C─┤$RST"
GRID3S4="$C├─$F341$C─┼─$F342$C─┼─$F343$C─┼─$F344$C─┼─$F345$C─┤$RST"
GRID3S5="$C├─$F351$C─┼─$F352$C─┼─$F353$C─┼─$F354$C─┼─$F355$C─┤$RST"
GRID3S6="$C└─$F361$C─┴─$F362$C─┴─$F363$C─┴─$F364$C─┴─$F365$C─┘$RST"

GRID4S1="$C┌─$F411$C─┬─$F412$C─┬─$F413$C─┬─$F414$C─┬─$F415$C─┐$RST"
GRID4S2="$C├─$F421$C─┼─$F422$C─┼─$F423$C─┼─$F424$C─┼─$F425$C─┤$RST"
GRID4S3="$C├─$F431$C─┼─$F432$C─┼─$F433$C─┼─$F434$C─┼─$F435$C─┤$RST"
GRID4S4="$C├─$F441$C─┼─$F442$C─┼─$F443$C─┼─$F444$C─┼─$F445$C─┤$RST"
GRID4S5="$C├─$F451$C─┼─$F452$C─┼─$F453$C─┼─$F454$C─┼─$F455$C─┤$RST"
GRID4S6="$C└─$F461$C─┴─$F462$C─┴─$F463$C─┴─$F464$C─┴─$F465$C─┘$RST"

GRID5S1="$C┌─$F511$C─┬─$F512$C─┬─$F513$C─┬─$F514$C─┬─$F515$C─┐$RST"
GRID5S2="$C├─$F521$C─┼─$F522$C─┼─$F523$C─┼─$F524$C─┼─$F525$C─┤$RST"
GRID5S3="$C├─$F531$C─┼─$F532$C─┼─$F533$C─┼─$F534$C─┼─$F535$C─┤$RST"
GRID5S4="$C├─$F541$C─┼─$F542$C─┼─$F543$C─┼─$F544$C─┼─$F545$C─┤$RST"
GRID5S5="$C├─$F551$C─┼─$F552$C─┼─$F553$C─┼─$F554$C─┼─$F555$C─┤$RST"
GRID5S6="$C└─$F561$C─┴─$F562$C─┴─$F563$C─┴─$F564$C─┴─$F565$C─┘$RST"



################################################################
## SCALE INFO:

# set KEY and GRADES:
case $ROOT in
    A)      KEY=101;;
    A#|Bb)  KEY=102;;
    B|Cb)   KEY=103;;
    C|B#)   KEY=104;;
    C#|Db)  KEY=105;;
    D)      KEY=106;;
    D#|Eb)  KEY=107;;
    E|Fb)   KEY=108;;
    F)      KEY=109;;
    F#|Gb)  KEY=110;;
    G)      KEY=111;;
    G#|Ab)  KEY=112;;
esac

case $INNOTE in
A) GRADE1="A";GRADE2="B";GRADE3="C";GRADE4="D";GRADE5="E";GRADE6="F";GRADE7="G";;
B) GRADE7="A";GRADE1="B";GRADE2="C";GRADE3="D";GRADE4="E";GRADE5="F";GRADE6="G";;
C) GRADE6="A";GRADE7="B";GRADE1="C";GRADE2="D";GRADE3="E";GRADE4="F";GRADE5="G";;
D) GRADE5="A";GRADE6="B";GRADE7="C";GRADE1="D";GRADE2="E";GRADE3="F";GRADE4="G";;
E) GRADE4="A";GRADE5="B";GRADE6="C";GRADE7="D";GRADE1="E";GRADE2="F";GRADE3="G";;
F) GRADE3="A";GRADE4="B";GRADE5="C";GRADE6="D";GRADE7="E";GRADE1="F";GRADE2="G";;
G) GRADE2="A";GRADE3="B";GRADE4="C";GRADE5="D";GRADE6="E";GRADE7="F";GRADE1="G";;
GRADES) GRADE1="I";GRADE2="II";GRADE3="III";GRADE4="IV";GRADE5="V";GRADE6="VI";GRADE7="VII";;
esac


# set the diatonic chords, the transposing values, and the transposed notes
case $SCALE in
    ##family natural
    major|ionian|naturalmode1)
        ALIAS="Major , Ionian"
        INFOMODE="Natural Mode 1"
        USAGE="usage chords and cadencies"
        INTERVALSTYPE="I        II        III       IV         V        VI        VII        I"
        CHORD1=maj7;CHORD2=m7;CHORD3=m7;CHORD4=maj7;CHORD5=7;CHORD6=m7;CHORD7=m7b5
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=5;TRAN5=7;TRAN6=9;TRAN7=11
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    dorian|naturalmode2)
        ALIAS="Dorian"
        INFOMODE="Natural Mode 2"
        INTERVALSTYPE="I        II       $BLD♭III$RST$C       IV         V        VI       $BLD♭VII $RST$C       I"
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=5;TRAN5=7;TRAN6=9;TRAN7=10
        CHORD7=maj7;CHORD1=m7;CHORD2=m7;CHORD3=maj7;CHORD4=7;CHORD5=m7;CHORD6=m7b5
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    phrygian|naturalmode3)
        ALIAS="Phrygian"
        INFOMODE="Natural Mode 3"
        INTERVALSTYPE="I        $BLD♭II      ♭III$RST$C       IV         V        $BLD♭VI      ♭VII$RST$C        I"
        TRAN1=0;TRAN2=1;TRAN3=3;TRAN4=5;TRAN5=7;TRAN6=8;TRAN7=10
        CHORD6=maj7;CHORD7=m7;CHORD1=m7;CHORD2=maj7;CHORD3=7;CHORD4=m7;CHORD5=m7b5
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    lydian|naturalmode4)
        ALIAS="Lydian"
        INFOMODE="Natural Mode 4"
        INTERVALSTYPE="I        II        III       $BLD♯IV$RST$C        V        VI        VII        I"
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=6;TRAN5=7;TRAN6=9;TRAN7=11
        CHORD5=maj7;CHORD6=m7;CHORD7=m7;CHORD1=maj7;CHORD2=7;CHORD3=m7;CHORD4=m7b5
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    mixolydian|naturalmode5)
        ALIAS="Mixolydian"
        INFOMODE="Natural Mode 5"
        INTERVALSTYPE="I        II        III       IV         V        VI       $BLD♭VII$RST$C        I"
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=5;TRAN5=7;TRAN6=9;TRAN7=10
        CHORD4=maj7;CHORD5=m7;CHORD6=m7;CHORD7=maj7;CHORD1=7;CHORD2=m7;CHORD3=m7b5
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    aeolian|minor|natural|naturalminor|naturalmode6)
        ALIAS="Aeolian, Minor, Natural Minor"
        INFOMODE="Natural Mode 6"
        INTERVALSTYPE="I        II       $BLD♭III$RST$C       IV         V        $BLD♭VI      ♭VII$RST$C        I"
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=5;TRAN5=7;TRAN6=8;TRAN7=10
        CHORD3=maj7;CHORD4=m7;CHORD5=m7;CHORD6=maj7;CHORD7=7;CHORD1=m7;CHORD2=m7b5
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    locrian|naturalmode7)
        ALIAS="Locrian"
        INFOMODE="Natural Mode 7"
        INTERVALSTYPE="I        $BLD♭II      ♭III$RST$C       IV        $BLD♭V        ♭VI      ♭VII$RST$C        I"
        TRAN1=0;TRAN2=1;TRAN3=3;TRAN4=5;TRAN5=6;TRAN6=8;TRAN7=10
        CHORD2=maj7;CHORD3=m7;CHORD4=m7;CHORD5=maj7;CHORD6=7;CHORD7=m7;CHORD1=m7b5
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;

    ##family melodic
    melodic|melodicminor|jazzminor|melodicmode1)
        ALIAS="Melodic , Melodic Minor , Jazz Minor"
        INFOMODE="Melodic Mode 1"
        INTERVALSTYPE="I        II       $BLD♭III$RST$C       IV         V        VI        VII        I"
        CHORD1=mMaj7;CHORD2=susb9;CHORD3=+maj7;CHORD4=7#11;CHORD5=7b13;CHORD6=m7b5;CHORD7=7alt
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=5;TRAN5=7;TRAN6=9;TRAN7=11
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    dorianb9|phrygian#13|melodicmode2)
        ALIAS="Dorian ♭9 , Phrygian ♯13"
        INFOMODE="Melodic Mode 2"
        INTERVALSTYPE="I        $BLD♭II      ♭III$RST$C       IV         V        VI       $BLD♭VII$RST$C        I"
        CHORD7=mMaj7;CHORD1=susb9;CHORD2=+maj7;CHORD3=7#11;CHORD4=7b13;CHORD5=m7b5;CHORD6=7alt
        TRAN1=0;TRAN2=1;TRAN3=3;TRAN4=5;TRAN5=7;TRAN6=9;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    lydianaugmented|lydian#5|melodicmode3)
        ALIAS="Lydian Augmented , Lydian ♯5"
        INFOMODE="Melodic Mode 3"
        INTERVALSTYPE="I        II        III       $BLD♯IV       ♯V$RST$C        VI        VII        I"
        CHORD6=mMaj7;CHORD7=susb9;CHORD1=+maj7;CHORD2=7#11;CHORD3=7b13;CHORD4=m7b5;CHORD5=7alt
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=6;TRAN5=8;TRAN6=9;TRAN7=11
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    lydiandominant|lydianb7|overtone|melodicmode4)
        ALIAS="Lydian Dominant , Lydian♭7 , Overtone"
        INFOMODE="Melodic Mode 4"
        INTERVALSTYPE="I        II        III       $BLD♯IV$RST$C        V        VI       $BLD♭VII$RST$C        I"
        CHORD5=mMaj7;CHORD6=susb9;CHORD7=+maj7;CHORD1=7#11;CHORD2=7b13;CHORD3=m7b5;CHORD4=7alt
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=6;TRAN5=7;TRAN6=9;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    mixolydianb13|hindu|melodicmode5)
        ALIAS="Mixolydian ♭13 , Hindu"
        INFOMODE="Melodic Mode 5"
        INTERVALSTYPE="I        II        III       IV         V        $BLD♭VI      ♭VII$RST$C        I"
        CHORD4=mMaj7;CHORD5=susb9;CHORD6=+maj7;CHORD7=7#11;CHORD1=7b13;CHORD2=m7b5;CHORD3=7alt
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=5;TRAN5=7;TRAN6=8;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    aeolianb5|locrian#9|halfdiminished|melodicmode6)
        ALIAS="Aeolian ♭5 , Locrian ♯9 , Half Diminished"
        INFOMODE="Melodic Mode 6"
        INTERVALSTYPE="I        II       $BLD♭III$RST$C       IV        $BLD♭V        ♭VI      ♭VII$RST$C        I"
        CHORD3=mMaj7;CHORD4=susb9;CHORD5=+maj7;CHORD6=7#11;CHORD7=7b13;CHORD1=m7b5;CHORD2=7alt
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=5;TRAN5=6;TRAN6=8;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    altered|superlocrian|locrianb11|diminishedwholetone|melodicmode7)
        ALIAS="Altered , Superlocrian , Locrian ♭11 , Diminished Wholetone"
        INFOMODE="Melodic Mode 7"
        INTERVALSTYPE="I        $BLD♭II      ♭III       ♭IV       ♭V        ♭VI      ♭VII$RST$C        I"
        CHORD2=mMaj7;CHORD3=susb9;CHORD4=+maj7;CHORD5=7#11;CHORD6=7b13;CHORD7=m7b5;CHORD1=7alt
        TRAN1=0;TRAN2=1;TRAN3=3;TRAN4=4;TRAN5=6;TRAN6=8;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;

    ##family harmonic minor
    harmonic|harmonicminor|harmonicmode1)
        ALIAS="Harmonic , Harmonic Minor"
        INFOMODE="Harmonic Mode 1"
        INTERVALSTYPE="I        II       $BLD♭III$RST$C       IV         V        $BLD♭VI$RST$C       VII        I"
        CHORD1=mMaj7;CHORD2=m7b5;CHORD3=+maj7;CHORD4=m7;CHORD5=7;CHORD6=maj7;CHORD7=dim7
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=5;TRAN5=7;TRAN6=8;TRAN7=11
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    locrian#13|harmonicmode2)
        ALIAS="Locrian ♯13"
        INFOMODE="Harmonic Mode 2"
        INTERVALSTYPE="I        $BLD♭II      ♭III$RST$C       IV        $BLD♭V$RST$C        VI       $BLD♭VII$RST$C        I"
        CHORD7=mMaj7;CHORD1=m7b5;CHORD2=+maj7;CHORD3=m7;CHORD4=7;CHORD5=maj7;CHORD6=dim7
        TRAN1=0;TRAN2=1;TRAN3=3;TRAN4=5;TRAN5=6;TRAN6=9;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    ionian#5|augmentedmajor|harmonicmode3)
        ALIAS="Ionian ♯5 , Augmented Major"
        INFOMODE="Harmonic Mode 3"
        INTERVALSTYPE="I        II        III       IV        $BLD♯V$RST$C        VI        VII        I"
        CHORD6=mMaj7;CHORD7=m7b5;CHORD1=+maj7;CHORD2=m7;CHORD3=7;CHORD4=maj7;CHORD5=dim7
        TRAN1=0;TRAN2=2;TRAN3=4;TRAN4=5;TRAN5=8;TRAN6=9;TRAN7=11
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    dorian#11|ukraniandorian|ukranian|romanian|romanianminor|altereddorian|harmonicmode4)
        ALIAS="Dorian ♯11 , Ukranian Dorian , Romanian Minor , Altered Dorian"
        INFOMODE="Harmonic Mode 4"
        INTERVALSTYPE="I        II       $BLD♭III       ♯IV$RST$C        V        VI       $BLD♭VII$RST$C        I"
        CHORD5=mMaj7;CHORD6=m7b5;CHORD7=+maj7;CHORD1=m7;CHORD2=7;CHORD3=maj7;CHORD4=dim7
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=6;TRAN5=7;TRAN6=9;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    phrygiandominant|mixolydianb9b13|harmonicmode5)
        ALIAS="Phrygian Dominant , Mixolydian ♭9♭13"
        INFOMODE="Harmonic Mode 5"
        INTERVALSTYPE="I        $BLD♭II$RST$C       III       IV         V        $BLD♭VI      ♭VII$RST$C        I"
        CHORD4=mMaj7;CHORD5=m7b5;CHORD6=+maj7;CHORD7=m7;CHORD1=7;CHORD2=maj7;CHORD3=dim7
        TRAN1=0;TRAN2=1;TRAN3=4;TRAN4=5;TRAN5=7;TRAN6=8;TRAN7=10
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    lydian#9|harmonicmode6)
        ALIAS="Lydian ♯9"
        INFOMODE="Harmonic Mode 6"
        INTERVALSTYPE="I        $BLD♯II$RST$C       III       $BLD♯IV$RST$C        V        VI        VII        I"
        CHORD3=mMaj7;CHORD4=m7b5;CHORD5=+maj7;CHORD6=m7;CHORD7=7;CHORD1=maj7;CHORD2=dim7
        TRAN1=0;TRAN2=3;TRAN3=4;TRAN4=6;TRAN5=7;TRAN6=9;TRAN7=11
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
    altereddiminished|locrianb11b7|harmonicmode7)
        ALIAS="Altered Diminished , Locrian ♭11♭7"
        INFOMODE="Harmonic Mode 7"
        INTERVALSTYPE="I        $BLD♭II      ♭III       ♭IV       ♭V        ♭VI      ♭♭VII$RST$C       I"
        CHORD2=mMaj7;CHORD3=m7b5;CHORD4=+maj7;CHORD5=m7;CHORD6=7;CHORD7=maj7;CHORD1=dim7
        TRAN1=0;TRAN2=1;TRAN3=3;TRAN4=4;TRAN5=6;TRAN6=8;TRAN7=9
        for i in {1..7};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;

    ##Pentatonics
    minorpentatonic|minorbluespentatonic)
        ALIAS="Minor Pentatonic , Minor Blues Pentatonic"
        INFOMODE=" "
        USAGE="usage chords and cadencies"
        INTERVALSTYPE="I $RST                ♭III       IV     $ITA$C (blues)$RST      V       ♭VII       $C I"
        TRAN1=0;TRAN2=3;TRAN3=5;TRAN4=6;TRAN5=7;TRAN6=10
        for i in {1..6};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;

    majorpentatonic|majorbluespentatonic)
        ALIAS="Major Pentatonic , Major Blues Pentatonic"
        INFOMODE=" "
        USAGE="usage chords and cadencies"
        INTERVALSTYPE="I  $RST      II     $ITA$C (blues)$RST     III        V        VI                  $C I"
        TRAN1=0;TRAN2=2;TRAN3=3;TRAN4=4;TRAN5=7;TRAN6=9
        for i in {1..6};do eval "NOTE$i=$(($KEY+$"TRAN$i"))";done
        ;;
esac

## setting the complete grade, and obtaining the final note name:
if [ $INNOTE != "GRADES" ] && [ $INNOTE != "PENTAGRADES" ]; then
for i in {1..7};do
    eval "GRADE$i=$"GRADE$i"$"NOTE$i""
    eval "notecheck=$"GRADE$i""
    case $notecheck in
        A101|A113) eval "GRADE$i=A";;
        A102|A114) eval "GRADE$i=A#";;
        A103|A115) eval "GRADE$i=A##";;
        B101|B113) eval "GRADE$i=Bbb";;
        B102|B114) eval "GRADE$i=Bb";;
        B103|B115) eval "GRADE$i=B";;
        B104|B116) eval "GRADE$i=B#";;
        B105|B117) eval "GRADE$i=B##";;
        C102|C114) eval "GRADE$i=Cbb";;
        C103|C115) eval "GRADE$i=Cb";;
        C104|C116) eval "GRADE$i=C";;
        C105|C117) eval "GRADE$i=C#";;
        C106|C118) eval "GRADE$i=C##";;
        D104|D116) eval "GRADE$i=Dbb";;
        D105|D117) eval "GRADE$i=Db";;
        D106|D118) eval "GRADE$i=D";;
        D107|D119) eval "GRADE$i=D#";;
        D108|D120) eval "GRADE$i=D##";;
        E106|E118) eval "GRADE$i=Ebb";;
        E107|E119) eval "GRADE$i=Eb";;
        E108|E120) eval "GRADE$i=E";;
        E109|E121) eval "GRADE$i=E#";;
        E110|E122) eval "GRADE$i=E##";;
        F107|F119) eval "GRADE$i=Fbb";;
        F108|F120) eval "GRADE$i=Fb";;
        F109|F121) eval "GRADE$i=F";;
        F110|F122) eval "GRADE$i=F#";;
        F111|F123) eval "GRADE$i=F##";;
        G109|G121) eval "GRADE$i=Gbb";;
        G110|G122) eval "GRADE$i=Gb";;
        G111|G123) eval "GRADE$i=G";;
        G112|G124) eval "GRADE$i=G#";;
        G113|G125) eval "GRADE$i=G##";;
        A111|G123) eval "GRADE$i=Abb";;
        A112|G127) eval "GRADE$i=Ab";;
    esac
done
fi

## Setting the diatonic chords
case $SCALE in
    minorpentatonic)
    DIATONICCHORDS="Diatonic chords:$RST $BLD\n
    I"$C2"m7   "$BLD"IV"$C2"m7   "$BLD"V"$C2"m7  \n";;
    majorpentatonic)
    DIATONICCHORDS="Diatonic chords:$RST $BLD\n
    I"$C2"7    "$BLD"I"$C2"V7    "$BLD"V"$C2"7   \n";;
    *)
    DIATONICCHORDS="Diatonic chords:$RST $BLD\n
    $GRADE1$C2$CHORD1  $BLD$GRADE2$C2$CHORD2  $BLD$GRADE3$C2$CHORD3  $BLD$GRADE4$C2$CHORD4  $BLD$GRADE5$C2$CHORD5  $BLD$GRADE6$C2$CHORD6  $BLD$GRADE7$C2$CHORD7    \n";;
esac

################################################################
##PIANO SETTING:

declare P1{01..27}=" "
NOTES=($NOTE1 $NOTE2 $NOTE3 $NOTE4 $NOTE5 $NOTE6 $NOTE7)
for i in ${NOTES[@]}; do
    eval "P$i=█"
done

PIANO="$C┌──┬─┬──┬──┬─┬─┬─┬──┬──┬─┬─┬─┬─┬─┬──┬──┬─┬─┬─┬──┬──┬─┬─┬─┬─┬─┬──┐
│  │$P102│  │  │$P105│ │$P107│  │  │$P110│ │$P112│ │$P114│  │  │$P117│ │$P119│  │  │$P122│ │$P124│ │$P126│  │
│  │$P102│  │  │$P105│ │$P107│  │  │$P110│ │$P112│ │$P114│  │  │$P117│ │$P119│  │  │$P122│ │$P124│ │$P126│  │
│ $P101└┬┘$P103 │ $P104└┬┘$P106└┬┘$P108 │ $P109└┬┘$P111└┬┘$P113└┬┘$P115 │ $P116└┬┘$P118└┬┘$P120 │ $P121└┬┘$P123└┬┘$P125└┬┘$P127 │
│ $P101 │ $P103 │ $P104 │ $P106 │ $P108 │ $P109 │ $P111 │ $P113 │ $P115 │ $P116 │ $P118 │ $P120 │ $P121 │ $P123 │ $P125 │ $P127 │
└───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┴───┘
$RST"


################################################################
## OUTPUT DISPLAY
################################################################

if [ $ONLYCHORDS = "ON" ]; then
    echo ""
else
    if [ $ROOT = "OFF" ];then
        echo -e "\n$BCK$BLD       $ALIAS        $RST"
    else
        echo $ROOT | grep -qE "(b$|#$)"
        if [ $? = 0 ];then
        echo -e "\n$BCK$BLD  [$ROOT] $ALIAS        $RST"
        else
        echo -e "\n$BCK$BLD   [$ROOT] $ALIAS        $RST"
        fi
    fi

    echo -e "$BCK       $INFOMODE        $RST"
    echo -e "$BLD
"$BLD"Scale intervals:$RST$C

├───$RST$in1$C───┼───$RST$in2$C───┼───$RST$in3$C───┼───$RST$in4$C───┼───$RST$in5$C───┼───$RST$in6$C───┼───$RST$in7$C───┤
$INTERVALSTYPE


$BLD$DIATONICCHORDS$RST
"
    # Display the patterns in the correct order:
    case $ORDER in

    1) echo -e "$GRID1S1    $GRID2S1\n$GRID1S2    $GRID2S2\n$GRID1S3    $GRID2S3\n$GRID1S4    $GRID2S4\n$GRID1S5    $GRID2S5\n$GRID1S6    $GRID2S6\n
$GRID3S1    $GRID4S1\n$GRID3S2    $GRID4S2\n$GRID3S3    $GRID4S3\n$GRID3S4    $GRID4S4\n$GRID3S5    $GRID4S5\n$GRID3S6    $GRID4S6\n
$GRID5S1\n$GRID5S2\n$GRID5S3\n$GRID5S4\n$GRID5S5\n$GRID5S6\n";;

    2) echo -e "$GRID2S1    $GRID3S1\n$GRID2S2    $GRID3S2\n$GRID2S3    $GRID3S3\n$GRID2S4    $GRID3S4\n$GRID2S5    $GRID3S5\n$GRID2S6    $GRID3S6\n
$GRID4S1    $GRID5S1\n$GRID4S2    $GRID5S2\n$GRID4S3    $GRID5S3\n$GRID4S4    $GRID5S4\n$GRID4S5    $GRID5S5\n$GRID4S6    $GRID5S6\n
$GRID1S1\n$GRID1S2\n$GRID1S3\n$GRID1S4\n$GRID1S5\n$GRID1S6\n";;

    3) echo -e "$GRID3S1    $GRID4S1\n$GRID3S2    $GRID4S2\n$GRID3S3    $GRID4S3\n$GRID3S4    $GRID4S4\n$GRID3S5    $GRID4S5\n$GRID3S6    $GRID4S6\n
$GRID5S1    $GRID1S1\n$GRID5S2    $GRID1S2\n$GRID5S3    $GRID1S3\n$GRID5S4    $GRID1S4\n$GRID5S5    $GRID1S5\n$GRID5S6    $GRID1S6\n
$GRID2S1\n$GRID2S2\n$GRID2S3\n$GRID2S4\n$GRID2S5\n$GRID2S6\n";;

    4) echo -e "$GRID4S1    $GRID5S1\n$GRID4S2    $GRID5S2\n$GRID4S3    $GRID5S3\n$GRID4S4    $GRID5S4\n$GRID4S5    $GRID5S5\n$GRID4S6    $GRID5S6\n
$GRID1S1    $GRID2S1\n$GRID1S2    $GRID2S2\n$GRID1S3    $GRID2S3\n$GRID1S4    $GRID2S4\n$GRID1S5    $GRID2S5\n$GRID1S6    $GRID2S6\n
$GRID3S1\n$GRID3S2\n$GRID3S3\n$GRID3S4\n$GRID3S5\n$GRID3S6\n";;

    5) echo -e "$GRID5S1    $GRID1S1\n$GRID5S2    $GRID1S2\n$GRID5S3    $GRID1S3\n$GRID5S4    $GRID1S4\n$GRID5S5    $GRID1S5\n$GRID5S6    $GRID1S6\n
$GRID2S1    $GRID3S1\n$GRID2S2    $GRID3S2\n$GRID2S3    $GRID3S3\n$GRID2S4    $GRID3S4\n$GRID2S5    $GRID3S5\n$GRID2S6    $GRID3S6\n
$GRID4S1\n$GRID4S2\n$GRID4S3\n$GRID4S4\n$GRID4S5\n$GRID4S6\n";;
    esac

    echo -e "\n$PIANO\n\n\n"
fi


################################################################
## CHORDS FUNCTION
################################################################

if [ $SHOWCHORDS = "ON" ];then
    case $SCALE in
    minorpentatonic)
        CHORDS=("m7");;
    majorpentatonic)
        CHORDS=("7");;
    *)
        CHORDS=("$GRADE1$CHORD1" "$GRADE2$CHORD2" "$GRADE3$CHORD3" "$GRADE4$CHORD4" "$GRADE5$CHORD5" "$GRADE6$CHORD6" "$GRADE7$CHORD7");;
    esac

    for var in ${CHORDS[@]}; do
        ROOTNOTE=$(echo $var | grep -oE "^([A-G]|[A-G]#|[A-G]##|[A-G]b|[A-G]bb)")
        CHORDTYPE=$(echo $var | grep -oE "(ALL|[1-9]$|m[1-9]$|maj[1-9]$|m7b5$|halfdim|halfdim7|dim|dim7|diminished|diminished7|mmaj7|mMaj7|minmaj7|minormajor7|\+maj7|maj7#5|augmentedmajor7|augmaj7|susb9|7susb9|7b5|7#11|7#5|7b13|7alt|alt|altered7|7#5b9|7b9b13)$")

        F=───
        declare F{1..364}="$F"
        declare {a,b,c,d,e,f,g,h,i,j,k,l}="      "

        case $ROOTNOTE in
            A|G##|Bbb)
                RootS6="  [5] ";RootS5="  [0] ";RootS4="  [7] "
                RootS6b="  [5] ";RootS5b="  [12]";RootS4b="  [7] "
                RootS6c="  [5] ";RootS5c="  [12]";RootS4c="  [7] "
                RootS6d="  [5] ";RootS5d="  [12]";RootS4d="  [7] ";;
            A#|Bb|Cbb)
                RootS6="  [6] ";RootS5="  [1] ";RootS4="  [8] "
                RootS6b="  [6] ";RootS5b="  [1] ";RootS4b="  [8] "
                RootS6c="  [6] ";RootS5c="  [13]";RootS4c="  [8] "
                RootS6d="  [6] ";RootS5d="  [13]";RootS4d="  [8] ";;
            B|A##|Cb)
                RootS6="  [7] ";RootS5="  [2] ";RootS4="  [9] "
                RootS6b="  [7] ";RootS5b="  [2] ";RootS4b="  [9] "
                RootS6c="  [7] ";RootS5c="  [2] ";RootS4c="  [9] "
                RootS6d="  [7] ";RootS5d="  [14]";RootS4d="  [9] ";;
            C|B#|Dbb)
                RootS6="  [8] ";RootS5="  [3] ";RootS4="  [10]"
                RootS6b="  [8] ";RootS5b="  [3] ";RootS4b="  [10]"
                RootS6c="  [8] ";RootS5c="  [3] ";RootS4c="  [10]"
                RootS6d="  [8] ";RootS5d="  [3] ";RootS4d="  [10]";;
            C#|Db)
                RootS6="  [9] ";RootS5="  [4] ";RootS4="  [11]"
                RootS6b="  [9] ";RootS5b="  [4] ";RootS4b="  [11]"
                RootS6c="  [9] ";RootS5c="  [4] ";RootS4c="  [11]"
                RootS6d="  [9] ";RootS5d="  [4] ";RootS4d="  [11]";;
            D|C##|Ebb)
                RootS6="  [10]";RootS5="  [5] ";RootS4="  [0] "
                RootS6b="  [10]";RootS5b="  [5] ";RootS4b="  [12]"
                RootS6c="  [10]";RootS5c="  [5] ";RootS4c="  [12]"
                RootS6d="  [10]";RootS5d="  [5] ";RootS4d="  [12]";;
            D#|Eb|Fbb)
                RootS6="  [11]";RootS5="  [6] ";RootS4="  [1] "
                RootS6b="  [11]";RootS5b="  [6] ";RootS4b="  [1] "
                RootS6c="  [11]";RootS5c="  [6] ";RootS4c="  [13]"
                RootS6d="  [11]";RootS5d="  [6] ";RootS4d="  [13]";;
            E|D##|Fb)
                RootS6="  [0] ";RootS5="  [7] ";RootS4="  [2] "
                RootS6b="  [12]";RootS5b="  [7] ";RootS4b="  [2] "
                RootS6c="  [12]";RootS5c="  [7] ";RootS4c="  [2] "
                RootS6d="  [12]";RootS5d="  [7] ";RootS4d="  [14]";;
            F|E#|Gbb)
                RootS6="  [1] ";RootS5="  [8] ";RootS4="  [3] "
                RootS6b="  [1] ";RootS5b="  [8] ";RootS4b="  [3] "
                RootS6c="  [13]";RootS5c="  [8] ";RootS4c="  [3] "
                RootS6d="  [13]";RootS5d="  [8] ";RootS4d="  [3] ";;
            F#|Gb)
                RootS6="  [2] ";RootS5="  [9] ";RootS4="  [4] "
                RootS6b="  [2] ";RootS5b="  [9] ";RootS4b="  [4] "
                RootS6c="  [2] ";RootS5c="  [9] ";RootS4c="  [4] "
                RootS6d="  [14]";RootS5d="  [9] ";RootS4d="  [4] ";;
            G|F##|Abb)
                RootS6="  [3] ";RootS5="  [10]";RootS4="  [5] "
                RootS6b="  [3] ";RootS5b="  [10]";RootS4b="  [5] "
                RootS6c="  [3] ";RootS5c="  [10]";RootS4c="  [5] "
                RootS6d="  [3] ";RootS5d="  [10]";RootS4d="  [5] ";;
            G#|Ab)
                RootS6="  [4] ";RootS5="  [11]";RootS4="  [6] "
                RootS6b="  [4] ";RootS5b="  [11]";RootS4b="  [6] "
                RootS6c="  [4] ";RootS5c="  [11]";RootS4c="  [6] "
                RootS6d="  [4] ";RootS5d="  [11]";RootS4d="  [6] ";;
        esac

        case $CHORDTYPE in
            maj7|Maj7|M7)
                F161=$H1;F154=$NO;F142=$H7;F132=$H3;F121=$H5;F114=$NO
                F264=$NO;F251=$H1;F241=$CP;F243=$H5;F231=$CP;F232=$H7;F221=$CP;F223=$H3;F211=$H5
                F364=$NO;F354=$NO;F341=$H1;F331=$CP;F333=$H5;F321=$CP;F323=$H7;F311=$CP;F313=$H3
                a=$RootS6
                e=$RootS5
                i=$RootS4
	            ;;
            7)
	            F161=$H1;F154=$NO;F141=$Hb7;F132=$H3;F121=$H5;F114=$NO
            	F264=$NO;F251=$H1;F241=$CP;F243=$H5;F231=$CP;F231=$Hb7;F221=$CP;F223=$H3;F211=$H5
	            F364=$NO;F354=$NO;F341=$H1;F331=$CP;F333=$H5;F321=$CP;F322=$Hb7;F311=$CP;F313=$H3
	            a=$RootS6
	            e=$RootS5
	            i=$RootS4
	            ;;
            m7)
	            F161=$H1;F154=$NO;F141=$Hb7;F131=$Hb3;F121=$H5;F114=$NO
	            F264=$NO;F251=$H1;F241=$CP;F243=$H5;F231=$CP;F231=$Hb7;F221=$CP;F222=$Hb3;F211=$H5
	            F364=$NO;F354=$NO;F341=$H1;F331=$CP;F333=$H5;F321=$CP;F322=$Hb7;F311=$CP;F312=$Hb3
	            a=$RootS6
	            e=$RootS5
	            i=$RootS4
	            ;;
            m7b5|halfdim|halfdim7)
                F162=$H1; F142=$Hb7; F132=$Hb3; F121=$Hb5; F154=$NO; F114=$NO
	            F251=$H1; F242=$Hb5; F231=$Hb7; F222=$Hb3; F264=$NO; F214=$NO
	            F341=$H1; F332=$Hb5; F322=$Hb7; F312=$Hb3; F364=$NO; F354=$NO
	            b=$RootS6b
	            e=$RootS5
	            i=$RootS4
	            ;;
            dim|dim7|diminished7)
	            F162=$H1; F141=$Hbb7; F132=$Hb3; F121=$Hb5; F154=$NO; F114=$NO
	            F252=$H1; F243=$Hb5; F231=$Hbb7; F223=$Hb3; F264=$NO; F214=$NO
	            F341=$H1; F332=$Hb5; F321=$Hbb7; F312=$Hb3; F364=$NO; F354=$NO
	            b=$RootS6b
	            f=$RootS5b
	            i=$RootS4
	            ;;
            mmaj7|mMaj7|minmaj7|minormajor7)
	            F161=$H1; F153=$H5; F142=$H7; F131=$Hb3; F121=$H5; F111=$H1; F151=$CP; F141=$CP; F264=$NO
	            F251=$H1; F243=$H5; F232=$H7; F222=$Hb3; F211=$H5; F241=$CP; F231=$CP; F221=$CP; F364=$NO; F354=$NO
	            F341=$H1; F333=$H5; F323=$H7; F312=$Hb3
	            a=$RootS6
	            e=$RootS5
	            i=$RootS4
	            ;;
            +maj7|maj7#5|augmentedmajor7|augmaj7)
	            F161=$H1; F142=$H7; F132=$H3; F122=$Hs5; F154=$NO; F114=$NO
	            F251=$H1; F244=$Hs5; F232=$H7; F223=$H3; F264=$NO; F214=$NO
	            F341=$H1; F334=$Hs5; F323=$H7; F313=$H3; F364=$NO; F354=$NO
	            a=$RootS6
	            e=$RootS5
	            i=$RootS4
	            ;;
            susb9|7susb9)
	            F163=$H1; F143=$Hb7; F131=$Hb9; F121=$H4; F111=$Hb7; F154=$NO
	            F253=$H1; F233=$Hb7; F222=$Hb9; F211=$H4; F264=$NO; F244=$NO
	            F342=$H1; F332=$H4; F323=$Hb7; F311=$Hb9; F364=$NO; F354=$NO
	            c=$RootS6c
	            g=$RootS5c
	            j=$RootS4b
	            ;;
            7b5|7#11)
	            F162=$H1; F142=$Hb7; F133=$H3; F121=$Hs11; F154=$NO; F114=$NO
	            F252=$H1; F241=$H3; F232=$Hb7; F211=$Hs11; F264=$NO; F224=$NO
	            F341=$H1; F332=$Hs11; F322=$Hb7; F313=$H3; F364=$NO; F354=$NO
	            b=$RootS6b
	            f=$RootS5b
	            i=$RootS4
	            ;;
            7#5|7b13)
	            F161=$H1; F141=$Hb7; F132=$H3; F122=$Hb13; F154=$NO; F114=$NO
	            F252=$H1; F241=$H3; F232=$Hb7; F213=$Hb13; F264=$NO; F224=$NO
	            F341=$H1; F334=$Hb13; F322=$Hb7; F313=$H3; F364=$NO; F354=$NO
            	a=$RootS6
	            f=$RootS5b
	            i=$RootS4
	            ;;
            7alt|alt|altered7|7#5b9|7b9b13)
	            F161=$H1; F141=$Hb7; F132=$H3; F122=$Hs5; F112=$Hb9; F154=$NO
	            F252=$H1; F241=$H3; F232=$Hb7; F221=$Hb9; F213=$Hs5; F231=$CP; F264=$NO
	            a=$RootS6
	            f=$RootS5b
	            ;;
        esac

        GRID="$C
┌─$F111─┬─$F112─┬─$F113─┬─$F114─┐    ┌─$F211─┬─$F212─┬─$F213─┬─$F214─┐    ┌─$F311─┬─$F312─┬─$F313─┬─$F314─┐
├─$F121─┼─$F122─┼─$F123─┼─$F124─┤    ├─$F221─┼─$F222─┼─$F223─┼─$F224─┤    ├─$F321─┼─$F322─┼─$F323─┼─$F324─┤
├─$F131─┼─$F132─┼─$F133─┼─$F134─┤    ├─$F231─┼─$F232─┼─$F233─┼─$F234─┤    ├─$F331─┼─$F332─┼─$F333─┼─$F334─┤
├─$F141─┼─$F142─┼─$F143─┼─$F144─┤    ├─$F241─┼─$F242─┼─$F243─┼─$F244─┤    ├─$F341─┼─$F342─┼─$F343─┼─$F344─┤
├─$F151─┼─$F152─┼─$F153─┼─$F154─┤    ├─$F251─┼─$F252─┼─$F253─┼─$F254─┤    ├─$F351─┼─$F352─┼─$F353─┼─$F354─┤
└─$F161─┴─$F162─┴─$F163─┴─$F164─┘    └─$F261─┴─$F262─┴─$F263─┴─$F264─┘    └─$F361─┴─$F362─┴─$F363─┴─$F364─┘

$a$b$c$d     $e$f$g$h     $i$j$k$l\n\n\n"

        echo -e "$BLD\n$BCK   Chord: $var    $RST$UND                                                               $RST"
        echo -e "$GRID$RST"
    done
fi

################################################################
## PDF FUNCTION
################################################################
if [[ $PDF = ON ]];then
    echo -e "\n\n"$BLU"Printing the output into a PDF file"

    ######### Check if aha & wkhtmltopdf are installed #################
    which aha | grep -q "aha"
    if [ $? != 0 ]; then AHA="NOTINSTALLED";INSTALL1="aha"; fi
    which wkhtmltopdf | grep -q "wkhtmltopdf"
    if [ $? != 0 ]; then WKH="NOTINSTALLED";INSTALL2="wkhtmltopdf"; fi

    if [[ $AHA = NOTINSTALLED ]] || [[ $WKH = NOTINSTALLED ]]; then
        echo -e "\n $RST$BLD It seems that the necessary packages to export to PDF are not installed, but you can install them with:

        $RST$YLW sudo apt install $INSTALL1 $INSTALL2$RST

$BLD$BLU Do you want to auto-run this command now? $RST$BLD(y/n)$RST"
        read INSTALL
            if [[ $INSTALL = y ]]; then
                sudo apt install $INSTALL1 $INSTALL2
            else
                exit
            fi
    fi

    ########## Printing ################################################
    if [[ $ROOT != OFF ]] && [[ $SHOWCHORDS = ON ]]; then
        FILEFOO="$ROOT $SCALE"
        cmd1="$0 $ROOT $SCALE"
        cmd2="$0 $ROOT $SCALE onlychords"
    elif [[ $ROOT != OFF ]] && [[ $SHOWCHORDS = OFF ]]; then
        FILEFOO="$ROOT $SCALE"
        cmd1="$0 $ROOT $SCALE"
    elif [[ $ROOT = OFF ]] && [[ $SHOWCHORDS = ON ]]; then
        FILEFOO="$SCALE"
        cmd1="$0 $SCALE"
        cmd2="$0 $SCALE onlychords"
    else
        FILEFOO="$SCALE"
        cmd1="$0 $SCALE"
    fi

    if [ -n "$cmd2" ]; then
        if [[ $ONLYCHORDS = ON ]]; then
            $cmd2 | aha --style "font-size:1.8em;line-height:100%" > "$FILEFOO".html; wkhtmltopdf "$FILEFOO".html "$FILEFOO - only chords".pdf
            if [ $? = 0 ];then
                rm "$FILEFOO".html
                echo -e "\n$BLD 🥳🎊 PDF saved at "$GRN""$(pwd)"/"$FILEFOO" onlychords.pdf$RST\n\n"
            else
                echo -e "\n$BLD$RED ⚠️ An error has ocurred and your PDF was not created. $RST"
            fi
        else
            $cmd1 | aha --style "font-size:1.8em;line-height:100%" > part1.html
            $cmd2 | aha --style "font-size:1.8em;line-height:100%" > part2.html
            wkhtmltopdf part1.html part1.pdf
            wkhtmltopdf part2.html part2.pdf
            pdfunite part1.pdf part2.pdf "$FILEFOO - with chords".pdf
            if [ $? = 0 ];then
                rm part1.html part2.html part1.pdf part2.pdf
                echo -e "\n$BLD 🥳🎊 PDF saved at "$GRN""$(pwd)"/"$FILEFOO".pdf$RST\n\n"
            else
                echo -e "\n$BLD$RED ⚠️ An error has ocurred and your PDF was not created. $RST"
            fi
        fi

    else
        $cmd1 | aha --style "font-size:1.8em;line-height:100%" > "$FILEFOO".html; wkhtmltopdf "$FILEFOO".html "$FILEFOO".pdf
        if [ $? = 0 ];then
            rm "$FILEFOO".html
            echo -e "\n$BLD 🥳🎊 PDF saved at "$GRN""$(pwd)"/"$FILEFOO".pdf$RST\n\n"
        else
            echo -e "\n$BLD$RED ⚠️ An error has ocurred and your PDF was not created. $RST"
        fi
    fi
fi
